language: php

php:
  - 7.1
  - 7.2
  - 7.3

env:
  global:
    - ILLUMINATE_VERSION=""
    - TESTBENCH_VERSION=""

  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""
    - ILLUMINATE_VERSION="5.7.*" TESTBENCH_VERSION="3.7.*"
    - ILLUMINATE_VERSION="5.8.*" TESTBENCH_VERSION="3.8.*"
    - ILLUMINATE_VERSION="6.*" TESTBENCH_VERSION="4.*"

matrix:
  exclude:
    - php: 7.1
      env: ILLUMINATE_VERSION="6.*" TESTBENCH_VERSION="4.*"

before_script:
  - travis_retry composer self-update
  - if [ "$ILLUMINATE_VERSION" != "" ] && [ "$TESTBENCH_VERSION" != "" ]; then
    composer require "illuminate/http:${ILLUMINATE_VERSION}" --no-update;
    composer require "illuminate/support:${ILLUMINATE_VERSION}" --no-update;
    composer require "orchestra/testbench:${TESTBENCH_VERSION}" --no-update;
    fi
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover